server:
  port: 8099
  servlet:
    context-path: /ogame

logging:
  level:
    root: INFO
    com.gumi.ogame: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:/home/sgumiel/personal/proyectos/ogamedb/ogamedb.db;
    username: ogame
    password: ogame
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
